apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app
    app.kubernetes.io/part-of: simple-nodejs-app
  name: simple-nodejs-appb51x
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: simple-nodejs-app
    weight: 100
status: {}
