apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: simple-nodejs-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: simple-nodejs-app
    app.kubernetes.io/part-of: simple-nodejs-app
  name: simple-nodejs-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: simple-nodejs-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: simple-nodejs-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rhn-support-djodha-tenant/simple-nodejs-app/simple-nodejs-app@sha256:a5062dd807c085ec73ebac6869da382fdbe07e23bc56c188b172503e3a327fdc
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
